In [2]:
import numpy as np

In [36]:
arr1 = np.arange(1,13, dtype=np.int32).reshape(3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arr1.ndim

2

In [10]:
arr1.shape

(3, 4)

In [11]:
arr1.size

12

In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr1.itemsize

4

In [15]:
arr2 = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
arr3=arr2.reshape((12))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
print(arr2, end='\n\n')
arr3=arr2.ravel()
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
print(arr2, end='\n\n')
arr4=arr2.flatten()
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
arr2 = np.arange(1,13, dtype=np.int32).reshape(3,4)
print(arr2)
arr5=arr2.resize(6,2)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [41]:
arr6=np.arange(1,28)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [51]:
arr2 = np.random.randn(6,6)
arr2

array([[ 1.16042767, -0.07598265, -0.26896994, -0.41917461, -2.05445911,
         0.41149401],
       [-0.31464397, -0.63565553,  0.0082561 , -2.12049921, -0.19799086,
         0.71182803],
       [-0.37032323, -0.09439344,  1.66261174,  0.89564358,  0.01614459,
         0.29431615],
       [-1.30122287,  0.58489706,  1.04762929,  1.70118024,  1.09221838,
        -0.37803279],
       [ 2.47048065, -0.93557464, -0.4870838 ,  2.55223977, -0.14257465,
         1.06414229],
       [-0.54136217,  1.89142195,  0.50930261, -0.65244231, -1.21347983,
         1.28994551]])

In [49]:
arr2 = np.empty((6,6))
arr2

array([[0.03792412, 0.24741393, 0.74832978, 0.98910216, 0.22034848,
        0.69590911],
       [0.44242324, 0.06986208, 0.90922059, 1.64465834, 1.90375924,
        0.64589546],
       [0.74605561, 0.63609846, 0.08828151, 0.10744757, 2.68517431,
        0.17214442],
       [1.28640891, 1.34236375, 0.0254936 , 1.65527746, 0.94022114,
        0.57368839],
       [0.09723421, 0.28462725, 0.73942211, 0.17956494, 1.56054729,
        0.67342397],
       [1.16468115, 0.88068248, 0.05055467, 2.23840769, 0.35845812,
        0.93134752]])

In [53]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.ones_like(arr1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
np.zeros_like(arr1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
np.full((4,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [59]:
np.full_like(arr1,7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [64]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
arr3=np.asarray(([1,2,3],[3,4,5]))
arr3

array([[1, 2, 3],
       [3, 4, 5]])

In [74]:
print(arr3.dtype)
arr3=arr3.astype(np.int64)
arr3.dtype

float16


dtype('int64')

In [83]:
a = np.arange(4*4).reshape(4,4)
print(a)
a.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [86]:
a.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [87]:
print(a, end='\n\n')
b= a+5
print(b, end ='\n\n')
a.dot(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]



array([[ 86,  92,  98, 104],
       [262, 284, 306, 328],
       [438, 476, 514, 552],
       [614, 668, 722, 776]])

In [90]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(1,0,2)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [91]:
print(a)
a.swapaxes(2,1) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

In [4]:
n = np.array([1,2,3,-5,-6,-7])
np.abs(n)

array([1, 2, 3, 5, 6, 7])

In [13]:
m=np.square(n)
m

array([ 1,  4,  9, 25, 36, 49], dtype=int32)

In [14]:
np.sqrt(m)

array([1., 2., 3., 5., 6., 7.])

In [97]:
np.sum(m)

124

In [15]:
np.cumsum(m)

array([  1,   5,  14,  39,  75, 124], dtype=int32)

In [16]:
np.prod(m)

1587600

In [17]:
np.cumprod(m)

array([      1,       4,      36,     900,   32400, 1587600], dtype=int32)

In [18]:
np.power(n,3)

array([   1,    8,   27, -125, -216, -343], dtype=int32)

In [24]:
h=np.fabs(n/3)
h

array([0.33333333, 0.66666667, 1.        , 1.66666667, 2.        ,
       2.33333333])

In [25]:
f, w = np.modf(h)
print(w,f, sep="\n")

[0. 0. 1. 1. 2. 2.]
[0.33333333 0.66666667 0.         0.66666667 0.         0.33333333]


In [27]:
print(n)
print(m)
np.maximum(n,m)

[ 1  2  3 -5 -6 -7]
[ 1  4  9 25 36 49]


array([ 1,  4,  9, 25, 36, 49])

In [34]:
print(n)
print(m, end='\n\n')
l = np.fmax(n,m)
print(l)

[ 1  2  3 -5 -6 -7]
[ 1  4  9 25 36 49]

[ 1  4  9 25 36 49]


In [37]:
print(arr1)
np.sum(arr1, axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([10, 26, 42])

In [38]:
x=np.array([9,4,7,3,8,9,4])
np.sort(x)

array([3, 4, 4, 7, 8, 9, 9])

In [39]:
np.unique(x)

array([3, 4, 7, 8, 9])

In [45]:
print(x)
y=x>5
print(y)
y.any()

[9 4 7 3 8 9 4]
[ True False  True False  True  True False]


True

In [44]:
y.all()

False

In [46]:
print(x)
np.split(x,[2,4,6])

[9 4 7 3 8 9 4]


[array([9, 4]), array([7, 3]), array([8, 9]), array([4])]

In [48]:
print(x)
np.split(x,7)

[9 4 7 3 8 9 4]


[array([9]),
 array([4]),
 array([7]),
 array([3]),
 array([8]),
 array([9]),
 array([4])]

In [50]:
print(x)
np.where(x%3==0,'Yes','No')

[9 4 7 3 8 9 4]


array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No'], dtype='<U3')

In [51]:
a=np.array([1,3,5,6,7,8,9])
b=np.array([1,5,8,10,14])
np.in1d(b,a)

array([ True,  True,  True, False, False])

In [52]:
np.intersect1d(b,a)

array([1, 5, 8])

In [54]:
np.union1d(b,a)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 14])

In [55]:
np.setdiff1d(b,a)

array([10, 14])

In [60]:
print(b)
np.repeat(b,3)

[ 1  5  8 10 14]


array([ 1,  1,  1,  5,  5,  5,  8,  8,  8, 10, 10, 10, 14, 14, 14])

In [61]:
print(b)
np.tile(b,3)

[ 1  5  8 10 14]


array([ 1,  5,  8, 10, 14,  1,  5,  8, 10, 14,  1,  5,  8, 10, 14])