# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [242]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [243]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [244]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [247]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [252]:
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [257]:
x.ndim

1

8. Create a boolean array with all the True values

In [240]:
x = np.ones((2,3), dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [230]:
arr2d=np.arange(2*5).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [228]:
arr3d=np.arange(3*3*3).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [227]:
x = np.arange(10)
print(x)
x[::-1]

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [224]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [220]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [213]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(np.float16)

array([1., 2., 3., 4., 5.], dtype=float16)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [212]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [209]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
np.maximum(arr1,arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [191]:
arr = np.arange(10)
print(arr)
arr[arr%2!=0]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [192]:
arr = np.arange(10)
print(arr)
arr[arr%2!=0] = -1
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [187]:
arr = np.arange(10)
print(arr)
arr[(arr>4) & (arr<9) ] = 12
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [182]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
print(arr2d)
#np.where(arr2d==5,12,arr2d)
arr2d[1][1]=12
arr2d

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [176]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [173]:
x = np.arange(10).reshape(2,5)
print(x)
x[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [170]:
x = np.arange(10).reshape(2,5)
print(x)
x[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [166]:
x = np.array([[0,1,2,3,4],[5,6,7,8,9],[9,8,7,6,5],[0,1,2,3,4]])
print(x)
x[:2][:,2]


[[0 1 2 3 4]
 [5 6 7 8 9]
 [9 8 7 6 5]
 [0 1 2 3 4]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [141]:
x = np.random.randn(10,10)
print("Minimum Value= ", np.min(x))
print("Maximum Value= ", np.max(x))


Minimum Value=  -2.2592130923494276
Minimum Value=  2.8153306080589653


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [135]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
#np.unique(a[np.where(a==b)])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [129]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [124]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[names!='Will']



[[ 1.21482793e-01  1.75361095e+00 -7.91784021e-02  2.83425061e-01]
 [ 8.25321257e-03  7.75764289e-02  4.51435299e-01  1.90069964e+00]
 [ 6.94763644e-01 -4.97503857e-01  1.06925653e+00 -1.04273300e-01]
 [ 7.13984975e-01  8.07413784e-01 -1.15088698e+00 -4.81411087e-03]
 [-1.52919999e+00  1.30671432e-03  8.89728537e-01  1.09360521e+00]
 [-1.08167612e-01  8.40176120e-01  4.50808561e-01 -1.12850131e+00]
 [-1.85831994e-02 -7.43371144e-01  6.39513666e-01 -2.01554000e-01]]


array([[ 0.12148279,  1.75361095, -0.0791784 ,  0.28342506],
       [ 0.00825321,  0.07757643,  0.4514353 ,  1.90069964],
       [ 0.71398498,  0.80741378, -1.15088698, -0.00481411],
       [-0.10816761,  0.84017612,  0.45080856, -1.12850131],
       [-0.0185832 , -0.74337114,  0.63951367, -0.201554  ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [125]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[(names!='Will') & (names!='Joe')]


[[ 1.24008729  1.35006051 -0.17449685  1.17153516]
 [-1.09106723 -0.37242275  2.25029281  0.00451741]
 [ 0.08849315 -0.38982108 -0.64292279  0.56123501]
 [ 0.2761463   1.07414718  0.57265181 -1.56987914]
 [-0.24039522 -0.80689153  1.13100355 -1.45650861]
 [ 2.02457274 -0.47807432  0.25361539 -1.18431207]
 [-0.35667798 -0.43728303  0.76432219  0.48597934]]


array([[ 1.24008729,  1.35006051, -0.17449685,  1.17153516],
       [ 0.2761463 ,  1.07414718,  0.57265181, -1.56987914]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [92]:
a = np.arange(1,16,dtype=np.float16).reshape(5,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float16)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [263]:
a = np.arange(1,17,dtype=np.float16).reshape(2,2,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)

33. Swap axes of the array you created in Question 32

In [269]:
a = np.arange(1,17,dtype=np.float16).reshape(2,2,4)
a.swapaxes(2,1)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]], dtype=float16)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [82]:
a = np.random.randn(10)
print(a)
np.sqrt(np.where(a<0.5,0,a))


[-1.31066968 -0.98953527 -0.46308593  2.09770629  0.94236361  0.77176691
  0.09953677  0.51827373  0.5534803   1.16059886]


array([0.        , 0.        , 0.        , 1.44834605, 0.97075415,
       0.87850265, 0.        , 0.71991231, 0.74396257, 1.07731094])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [77]:
import numpy as np
a = np.random.randn(12) * 5
b = np.random.randn(12) * 5
print(a)
print(b)
np.maximum(a,b)                  


[ 5.05981892 -7.10667103 11.78159733 -0.96460999  1.7013511  -9.2477861
 -5.126176    0.4641589  -4.68475866  0.90458256  7.75247354  5.03134041]
[ 6.10354337 -2.52867467 -8.32498179 -0.48303916 -9.66786372 -4.29477724
 -1.67100814  6.09172908 -1.0333232  -9.59562517 -4.00512582  1.12885995]


array([ 6.10354337, -2.52867467, 11.78159733, -0.48303916,  1.7013511 ,
       -4.29477724, -1.67100814,  6.09172908, -1.0333232 ,  0.90458256,
        7.75247354,  5.03134041])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [49]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c= np.setdiff1d(a, b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [43]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = numpy.array([[10,10,10]])
delArray = numpy.delete(sampleArray,1,1)
numpy.insert(delArray,1,newColumn,1)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [44]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [45]:
arr1 = np.random.randn(20)*5
print(arr1)
np.cumsum(arr1)

[ 3.48101341 -2.995963    9.44018836 -5.26740074  8.47233605 -2.11825657
  6.49636599  2.30568051 -6.51105725 -9.61146901 10.83267347  3.74314503
 -0.19428701  4.49683173  1.80022969 -4.99239288 -1.72556755  0.84715556
  1.48742138 -1.45732798]


array([ 3.48101341,  0.48505041,  9.92523878,  4.65783803, 13.13017408,
       11.01191752, 17.5082835 , 19.81396401, 13.30290676,  3.69143775,
       14.52411123, 18.26725626, 18.07296925, 22.56980098, 24.37003067,
       19.37763779, 17.65207024, 18.4992258 , 19.98664717, 18.52931919])